# Generated by Django 3.0.8 on 2022-11-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='map',
            field=models.FileField(blank=True, upload_to='maps/', verbose_name='карта района'),
        ),
        migrations.AlterField(
            model_name='region',
            name='map',
            field=models.FileField(blank=True, upload_to='maps/', verbose_name='карта округа'),
        ),
    ]
