# Generated by Django 3.0.8 on 2022-12-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221123_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='title1',
            field=models.CharField(blank=True, max_length=50, verbose_name='заголовок1'),
        ),
        migrations.AddField(
            model_name='district',
            name='title2',
            field=models.CharField(blank=True, max_length=50, verbose_name='заголовок2'),
        ),
        migrations.AddField(
            model_name='district',
            name='title3',
            field=models.CharField(blank=True, max_length=50, verbose_name='заголовок3'),
        ),
        migrations.AddField(
            model_name='district',
            name='title4',
            field=models.CharField(blank=True, max_length=50, verbose_name='заголовок4'),
        ),
        migrations.AddField(
            model_name='district',
            name='title5',
            field=models.CharField(blank=True, max_length=50, verbose_name='заголовок5'),
        ),
        migrations.AddField(
            model_name='district',
            name='title6',
            field=models.CharField(blank=True, max_length=50, verbose_name='заголовок6'),
        ),
        migrations.AddField(
            model_name='district',
            name='title7',
            field=models.CharField(blank=True, max_length=50, verbose_name='заголовок7'),
        ),
    ]
