# Generated by Django 3.0.8 on 2023-02-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221201_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='map',
        ),
        migrations.AddField(
            model_name='region',
            name='svg',
            field=models.CharField(blank=True, max_length=30, verbose_name='svg'),
        ),
    ]
