# Generated by Django 3.0.8 on 2023-02-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230228_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='svg',
        ),
    ]
