# Generated by Django 3.0.8 on 2023-03-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_district_transit_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='transit_link',
            new_name='translit_link',
        ),
    ]
