# Generated by Django 3.0.8 on 2023-03-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230311_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='caption1',
            field=models.CharField(blank=True, max_length=50, verbose_name='подпись1'),
        ),
        migrations.AddField(
            model_name='district',
            name='caption2',
            field=models.CharField(blank=True, max_length=50, verbose_name='подпись2'),
        ),
        migrations.AddField(
            model_name='district',
            name='caption3',
            field=models.CharField(blank=True, max_length=50, verbose_name='подпись3'),
        ),
        migrations.AddField(
            model_name='district',
            name='caption4',
            field=models.CharField(blank=True, max_length=50, verbose_name='подпись4'),
        ),
        migrations.AddField(
            model_name='district',
            name='caption5',
            field=models.CharField(blank=True, max_length=50, verbose_name='подпись5'),
        ),
        migrations.AddField(
            model_name='district',
            name='caption6',
            field=models.CharField(blank=True, max_length=50, verbose_name='подпись6'),
        ),
        migrations.AddField(
            model_name='district',
            name='caption7',
            field=models.CharField(blank=True, max_length=50, verbose_name='подпись7'),
        ),
    ]
