# Generated by Django 3.0.8 on 2023-03-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230315_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='caption1',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись1'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption10',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись10'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption2',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись2'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption3',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись3'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption4',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись4'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption5',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись5'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption6',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись6'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption7',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись7'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption8',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись8'),
        ),
        migrations.AlterField(
            model_name='district',
            name='caption9',
            field=models.CharField(blank=True, max_length=100, verbose_name='подпись9'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title1',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок1'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title10',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок10'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title2',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок2'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title3',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок3'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title4',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок4'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title5',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок5'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title6',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок6'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title7',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок7'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title8',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок8'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title9',
            field=models.CharField(blank=True, max_length=100, verbose_name='заголовок9'),
        ),
    ]
